### PR TITLE
Fix time formatting between 0am and 1am

### PR DESCRIPTION
**Pull request by bertramakers**
### Fixed

- Fixed opening hours between `0:01` and `0:59` being displayed as `:01` and `:59`

### CODE REVIEW

**Comment by lucwollants** [comment]
Is an "extra" leading zero not dependent on working with a 24-hour or 12-hour clock?
See https://simple.wikipedia.org/wiki/12-hour_clock

So with a 24-hour clock, we always have 4 digits and with a 12-hour clock, we have a mix of 3 or 4 digits but never a leading zero.

**Comment by bertramakers** [comment]
I'm not sure, I just took the existing logic of removing the leading `0` and fixed it so times between `0:01` and `0:59` don't show up as `:01` and `:59`

**Comment by lucwollants** [comment]
Indeed the bug itself is fixed. Having the difference between a 12-hour and 24-hour clock is out of the scope of this fix.

**Review by lucwollants — APPROVED** [review]
Fixed!

**Comment by bertramakers** [comment]
Thanks! You can always check with @corneelwille if you want to be sure that the format used for the opening hours is correct in general, regardless of this bug fix.

**Pull request merged**
