### PR TITLE
Remove counting of newlines

### PR DESCRIPTION
**Pull request by bertramakers**
### Removed

- Removed counting of newlines

---

Follow up to #23

### CODE REVIEW

**Comment by bertramakers** [comment]
Actually I'm going to do this differently

**Review by jdrieghe — APPROVED** [review]
That's actually pretty clever 🎖️

**Comment by jdrieghe** [comment]
In that case, ignore what I said 😂

**Comment by bertramakers** [comment]
Heh I can still revert it if you prefer the first solution

**Review by jdrieghe — APPROVED** [review]
This is even cleaner 👏

**Pull request merged**
